In [5]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [7]:
iris = load_iris()

In [8]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [9]:
iris_lr = LogisticRegression()
iris_svm = SVC()
iris_rf = RandomForestClassifier()
iris_dt = DecisionTreeClassifier()


In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = .2)

In [12]:
len(X_train)

120

In [17]:
iris_lr.fit(X_test, y_test)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [18]:
iris_lr.score(X_test, y_test)

1.0

In [19]:
iris_svm.fit(X_test, y_test)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [20]:
iris_svm.score(X_test, y_test)

0.9666666666666667

In [21]:
iris_rf.fit(X_test, y_test)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [22]:
iris_rf.score(X_test, y_test)

1.0

In [23]:
iris_dt.fit(X_test, y_test)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [24]:
iris_dt.score(X_test, y_test)

1.0

In [27]:
iris_lr = cross_val_score(LogisticRegression(), X_test, y_test)
iris_lr


array([0.83333333, 1.        , 1.        , 1.        , 1.        ])

In [32]:
np.average(iris_lr)

0.9666666666666668

In [35]:
iris_svm = cross_val_score(SVC(), X_test, y_test)
iris_svm


array([1.        , 0.83333333, 1.        , 0.83333333, 1.        ])

In [36]:
np.average(iris_svm)

0.9333333333333333

In [37]:
iris_rf = cross_val_score(RandomForestClassifier(), X_test, y_test)
iris_rf


array([1., 1., 1., 1., 1.])

In [40]:
np.average(iris_rf)

1.0

In [39]:
iris_dt = cross_val_score(DecisionTreeClassifier(), X_test, y_test)
iris_dt


array([1., 1., 1., 1., 1.])

In [41]:
np.average(iris_dt)

1.0